### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by car12lin12** [car12lin12/InstaBaddies#78]
**Given :** 
- user30 has an account
- user40 has an account
- user30 is logged in

**When :** 
user30 asks to search for user40.

**Then :** 
user40's profile is displayed.

**Tasks :** 
- [x]  Frontend : add search bar in Navbar ( #79 )
- [x] Frontend & backend : handle onChange ( get all users in backend ) ( #80 )
- [x] Add preview for filtered users ( #80 )
- [x] Add redirect on list user ( #81 )
- [x] Handle no user found ( #82 )

Comments : 
- notification on no user found or not ?

**Comment by car12lin12** [comment]
resolved by #64 and #66
